### ISSUE TITLE
偶尔会执行失败

### ISSUE THREAD

**Issue by pexcn** [RookieBugs/CheckInActivities#1]
这里是我的 travis-ci 的 log: https://www.travis-ci.org/pexcn/CheckInActivities/builds/354992158
看起来像是 DNS 解析不出来的样子，能否加个重试机制？

**Comment by RookieBugs** [comment]
谢谢提醒，前天我也出现这个问题，最近事情比较多，过段时间研究研究

**Comment by pexcn** [comment]
好的，也许看看能不能在程序里面指定国内的dns解析，应该会好一点

**Comment by RookieBugs** [comment]
有想到输出exit code，判断程序执行是否成功

**Comment by pexcn** [comment]
嗯，还有就是最好是能换成 `urllib3` https://github.com/requests/requests/issues/3470#issuecomment-237470680 应该能指定国内 DNS

**Comment by pexcn** [comment]
我想，在 https://github.com/RookieBugs/CheckInActivities/blob/master/apps/ChinaUnicom.py#L59 处，请求网络的时候是不是应该要拋个异常出来？不然会出现 https://travis-ci.org/pexcn/CheckInActivities/builds/354992158 这种异常。

似乎重试的方式放在请求网络的时候更好？

**Comment by RookieBugs** [comment]
感谢提醒，一直没注意到每次报错其实是登陆请求失败，添加了两次重试机制，静观一段时间看看

**Comment by pexcn** [comment]
好 :)

**Comment by pexcn** [comment]
Fixed via https://github.com/RookieBugs/CheckInActivities/commit/f1fc79b9bbca46dd9d093afbcc4408abdf701009
